// app/layout.tsx
import { Metadata } from "next";
import {Providers} from "./providers";
import { Inter } from "next/font/google";
import MyHeader from "./Components/MyHeader";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: { children: React.ReactNode }) {
  return (
    <html lang="en" className='dark'>
      <MyHeader />
        <body>
          <Providers>
            {children}
          </Providers>
        </body>
    </html>
  );
}